### ISSUE TITLE
NaN values of depth in data

### ISSUE THREAD

**Issue by NoahDDavis** [marco-rudolph/AST#3] opened 2023-02-08 05:42 UTC
Hi thanks for the nice work?
However, when I run train_teacher.py file after preprocessing data, the depth data seems to have all NaN values.
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/101535753/217444643-21c2eeeb-9c0f-4f21-a2f0-233f3a0310f3.png">

Do you have any clues where the problem is?
Thanks

**Comment by marco-rudolph** [comment] 2023-02-08 09:26
Hi,
thanks!
Unfortunately, I cannot reproduce this error.
Have you installed all requirements?
Can you investigate from which point this error exists? Are these values NaN while running preprocess.npy (see lines 70-75)?

**Comment by marco-rudolph** [comment] 2023-02-14 11:02
As I heard from multiple people the code is working, I'll close this issue. If there is still a problem, you are welcome to reopen it and provide more details (see my post above).

**Closed as completed by marco-rudolph** 2023-02-14 11:02 UTC

**Comment by NoahDDavis** [comment] 2023-02-20 18:34
Thanks very much for your reply and comments and I have solved the issue.
One more question:
 as written in your code, there is max score over maps and mean score over maps, could you explain the difference, and which score did you use for the reported results in your paper?

Thanks in advance and I will appreciate it very much if you could reply.

**Comment by limaodaxia** [comment] 2024-01-25 23:48
> Thanks very much for your reply and comments and I have solved the issue. One more question: as written in your code, there is max score over maps and mean score over maps, could you explain the difference, and which score did you use for the reported results in your paper?
> 
> Thanks in advance and I will appreciate it very much if you could reply.

I also want to know the difference of mean and max.

**Comment by marco-rudolph** [comment] 2024-01-26 09:47
> > Thanks very much for your reply and comments and I have solved the issue. One more question: as written in your code, there is max score over maps and mean score over maps, could you explain the difference, and which score did you use for the reported results in your paper?
> > Thanks in advance and I will appreciate it very much if you could reply.
> 
> I also want to know the difference of mean and max.

You can find the explanation here: https://github.com/marco-rudolph/AST/issues/6

**Comment by jcjlin** [comment] 2024-01-31 05:09
I also faced the NaN issue mentioned above when running train_teacher.py after preprocessing, could I ask for the solutions please! Thanks a lot. (ValueError: Input contains NaN, infinity or a value too large for dtype('float32').)
